version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
